exploringearth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("destinations/", views.DestinationList.as_view(), name="destinations_list"),
    path(
        "destinations/<int:pk>/",
        views.DestinationDetail.as_view(),
        name="destinations_detail",
    ),
    path(
        "destinations/create/",
        views.DestinationCreate.as_view(),
        name="destinations_create",
    ),
    path(
        "destinations/<int:destination_id>/add_photo/",
        views.add_photo,
        name='add_photo',
    ),
    path(
        "destinations/<int:pk>/update/",
        views.DestinationUpdate.as_view(),
        name="destinations_update",
    ),
    path(
        "destinations/<int:pk>/delete/",
        views.DestinationDelete.as_view(),
        name="destinations_delete",
    ),
    path(
        "destinations/<int:destination_id>/add_photo/",
        views.add_photo,
        name="add_photo",
    ),
    path("comments/", views.CommentList.as_view(), name="comments_index"),
    path("comments/<int:pk>/", views.CommentDetail.as_view(), name="comments_detail"),
    path(
        "destinations/<int:destination_id>/comments/create/",
        views.CommentCreate.as_view(),
        name="comments_create",
    ),
    path(
        "comments/<int:pk>/update/",
        views.CommentUpdate.as_view(),
        name="comments_update",
    ),
    path(
        "comments/<int:pk>/delete/",
        views.CommentDelete.as_view(),
        name="comments_delete",
    ),
    path("accounts/signup/", views.signup, name="signup"),
    path("gallery/", views.PhotoList.as_view(), name="gallery"),
   
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.


class Destination(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    location = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.id})"

    def get_absolute_url(self):
        return reverse("destinations_detail", kwargs={"pk": self.id})


class Comment(models.Model):
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}'s comment on {self.destination}"

    def get_absolute_url(self):
        return reverse("destinations_detail", kwargs={"pk": self.destination_id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    caption = models.CharField(max_length=100)

    def __str__(self):
        return f"Photo for destination_id: {self.destination_id} @{self.url}"

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Destination, Comment, Photo


def home(request):
    destinations = Destination.objects.all()
    print(f"number of destinations - {len(destinations)}")
    context = { 'destinations' : destinations }
    return render(request, "home.html", context)


def about(request):
    return render(request, "about.html")


class DestinationList(LoginRequiredMixin, ListView):
    model = Destination
    fields = ["name", "description", "location", "user"]


class DestinationDetail(LoginRequiredMixin, DetailView):
    model = Destination
    fields = ["name", "description", "location", "user"]


class DestinationCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Destination
    fields = ["name", "description", "location"]

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect("/")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DestinationUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Destination
    fields = ["name", "description", "location"]

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect("/")


class DestinationDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Destination
    success_url = "/destinations"

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect("/")


class CommentList(LoginRequiredMixin, ListView):
    model = Comment
    fields = ["comment", "timestamp", "user", "destination"]


class CommentDetail(LoginRequiredMixin, DetailView):
    model = Comment
    fields = ["comment", "timestamp", "user", "destination"]

class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ["comment"]

    def form_valid(self, form):
        form.instance.destination_id = self.kwargs["destination_id"]
        form.instance.user = self.request.user
        return super().form_valid(form)


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ["comment"]


class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = "/destinations"


@login_required
def add_photo(request, destination_id):
    photo_file = request.FILES.get("photo-file", None)
    if photo_file:
        s3 = boto3.client("s3")
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind(".") :]
        try:
            bucket = os.environ["S3_BUCKET"]
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, destination_id=destination_id, caption=request.POST['caption'])
        except Exception as e:
            print("An error occurred uploading file to S3")
            print(e)
    return redirect("destinations_detail", pk=destination_id)


def signup(request):
    error_message = ""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
        else:
            error_message = "Invalid sign up - try again"
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

class PhotoList(LoginRequiredMixin, ListView):
    model = Photo

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="py-5">
  <div class="container text-center">
    <h1>Who we are</h1>
  </div><img class="w-100 py-5" src="{% static 'img/about-banner.jpg' %}" alt="">
  <div class="container">
    <div class="row gy-5">
      <div>
        <p class="lead first-letter-styled lh-4">
          We love to travel and with it we decided to make a blog that will cover most of the activities that can be done in the area. We also strive to find the best prices since not everyone has thousands of dollars as pocket change.
          We document our stay at locations around the world while maintaining a budgeting, so everyone can see how much you actually need to enjoy a trip out. There’s a lot of little gems that aren't expensive in really popular places and you don't really need a lot of money to still make memorable moments.
        </p>
        <div class="px-lg-5 mb-5">
          <blockquote class="blockquote-custom">
            You want to travel but no place goes in detail of what activities and attractions are in the area with pricing in mind.  
          </blockquote>
        </div>
        <h2>Team</h2>
        <p class="text-muted mb-0">
          We go into detail about what can be done in the destinations we’ve covered while maintaining a budget. Everyone wanted to travel and not spend too much? We got you covered with everything we found to be budget friendly and exceptional, along with things that may not be worth the cheap price.  
      </div>   
      <div class="col-lg-3">
        <h5 class="mb-1">Priyanka Nair</h5>
        <img src="{% static 'img/Priyanka.JPG' %}" alt="" width="200">
        <p class="small text-primary text-uppercase mb-0">Designer</p>
        <p class="small text-muted">Design, Document, Templates, Content</p>
      </div>
      <div class="col-lg-3">
        <h5 class="mb-1">Jay Donaldson</h5>
        <img src="{% static 'img/Jay.png' %}" alt="" width="190">
        <p class="small text-primary text-uppercase mb-0">Middle Management</p>
        <p class="small text-muted">GitHub Manager, Authentication, Views, Templates, Content</p>
      </div>
      <div class="col-lg-3">
        <h5 class="mb-1">Malcolm Griffin</h5>
        <img src="{% static 'img/Malcolm.jpeg' %}" alt="" width="190">
        <p class="small text-primary text-uppercase mb-0">Developer</p>
        <p class="small text-muted">Scrum Master, Templates, Content</p>          
      </div>
      <div class="col-lg-3">
        <h5 class="mb-1">Gary Lopez</h5>
        <img src="{% static 'img/Gary.jpeg' %}" alt="" width="190">
        <p class="small text-primary text-uppercase mb-0">Developer</p>
        <p class="small text-muted">Database Manager, Templates, content</p>
      </div>      
    </div>
  </div>
</section>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Exploring Earth</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'css/vendor/swiper/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:300,400&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap">
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
  </head>
  <body>
    <header class="header">
      <div class="py-2 bg-dark text-white">
        <div class="container py-1">
          <div class="row align-items-center">
            <div class="col-4">
              <ul class="list-inline mb-0 text-sm">
                <li class="list-inline-item"><a class="reset-anchor" href="{% url 'about' %}">About us</a></li>
                <li class="list-inline-item">|</li>
                <li class="list-inline-item"><a class="reset-anchor" href="{% url 'signup' %}">Sign Up</a></li>
              </ul>
            </div>
            <div class="col-4 d-block text-center">
              <ul class="list-inline mb-0 small">
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-facebook-f"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-youtube"></i></a></li>
                <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-vimeo-v"></i></a></li>
              </ul>
            </div>
            <div class="col-4 d-block text-end">
              <ul class="list-inline mb-0 text-sm">
                {% if user.is_superuser %}
                <li class="list-inline-item"><a class="reset-anchor" href="/admin">Admin</a></li>
                <li class="list-inline-item">|</li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="list-inline-item"><a class="reset-anchor" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="list-inline-item"><a class="reset-anchor" href="{% url 'login' %}">Login</a></li>
                {% endif %}
              </ul>              
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-expand-lg navbar-light bg-white py-4">
        <div class="container text-center">
          <a class="navbar-brand mx-auto" href="/about">
            <img  src="{% static 'img/logo.jpg' %}" alt="" width="400">
          </a>
        </div>
      </nav>
      <nav class="navbar navbar-expand-sm navbar-light border-gray py-2 bg-light">
        <div class="container">
          <div class="navbar-collapse collapse show" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item px-1">
                <a class="nav-link" href="/">Home</a>
              </li>
              {% if user.is_superuser %}
              <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'destinations_create' %}">Add Destination</a>
              </li>
              {% endif %}
              <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'destinations_list' %}">Destinations</a>
              </li>
              <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'gallery' %}">Gallery</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <section class="pt-5">
     <main class="container">
      {% block content %}
      {% endblock %}
      </main>
    </section>
    <br/><br/><br/><br/>
    <footer class="bg-dark py-4">
      <div class="container">
        <div class="row py-2 gy-2">
          <div class="col-lg-4 text-center text-lg-start">
            <p class="small text-muted text-uppercase mb-0">&copy; copyright 2023 - all rights reserved</p>
          </div>
          <div class="col-lg-4 text-center">
            <ul class="list-inline text-white small mb-0">
              <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-youtube"></i></a></li>
              <li class="list-inline-item"><a class="reset-anchor" href="#!"><i class="fab fa-vimeo-v"></i></a></li>
            </ul>
          </div>
          <div class="col-lg-4 text-center text-lg-end">
            <p class="small text-muted text-uppercase mb-0">Exploring Earth ! </p>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'css/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script>
      function injectSvgSprite(path) {
      
          var ajax = new XMLHttpRequest();
          ajax.open("GET", path, true);
          ajax.send();
          ajax.onload = function(e) {
          var div = document.createElement("div");
          div.className = 'd-none';
          div.innerHTML = ajax.responseText;
          document.body.insertBefore(div, document.body.childNodes[0]);
          }
      }
      injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg'); 
      
    </script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Featured Destinations</h1>        
<div class="swiper destinations-slider swiper-padding">
    <div class="swiper-wrapper">
        {% for destination in destinations %}
        <div class="swiper-slide h-auto">
            <a class="destination d-flex align-items-end bg-center bg-cover" href="{% url 'destinations_detail' destination.id %}" style="background: url({{destination.photo_set.first.url}})">
                <div class="destination-inner w-100 text-center text-white index-forward has-transition">
                    <h2 class="h3 mb-4">
                    {{destination.name}}
                    </h2>
                    <p class="small text-uppercase mb-3"> 
                    {{destination.location}}
                    </p>
                    <div class="btn btn-primary w-100 destination-btn text-white">Discover</div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="swiper-button-prev swiper-custom-nav text-uppercase letter-spacing-0">
        <svg class="svg-icon svg-icon me-1">
          <use xlink:href="#arrow-left-1"> </use>
        </svg>
        <span class="text-sm">Prev</span>
    </div>
    <div class="swiper-button-next swiper-custom-nav text-uppercase letter-spacing-0">
        <span class="text-sm">Next</span>
        <svg class="svg-icon svg-icon ms-1">
            <use xlink:href="#arrow-right-1"> </use>
        </svg>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Comment</h1>

  <h4>Are you sure you want to delete <span class="orange-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm!" class="btn">
    <a href="{% url 'comments_detail' comment.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/comment_detail.html
{% extends "base.html" %}
{% block content %}

<h1>{{comment.user}}'s comment for {{comment.destination.name}}</h1>
<h6>{{comment.timestamp}}</h6>
<br>
<p>{{comment.comment}}</p>
<div style="float: left">
    <a href="{% url "destinations_detail" comment.destination_id %}">Go Back</a>
</div>
<div style="float: right">
    {% if user == comment.user %}
    <a href="{% url "comments_update" comment.id %}">Edit</a> ||
    <a href="{% url "comments_delete" comment.id %}">Delete</a>
    {% endif %}
</div>
{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit Comment</h1>
  {% else %}
    <h1>Add Comment</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn btn-dark">
  </form>
{% endblock %}

main_app/templates/main_app/destination_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Destination</h1>

  <h4>Are you sure you want to delete <span class="orange-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm!" class="btn">
    <a href="{% url 'destinations_detail' destination.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/destination_detail.html
{% extends "base.html" %}
{% block content %}

<h1>{{ destination.name }}</h1>
<div>
    <div align="right">
        {% if user.is_superuser %}
        <a href="{% url "destinations_update" destination.id %}">Edit</a> || 
        <a href="{% url "destinations_delete" destination.id %}">Delete</a>
        {% endif %}
    </div>
    <p>Location: {{ destination.location }}</p>
    <p>Description: {{ destination.description }}</p>
    {% for photo in destination.photo_set.all %}
      <div align="center"><img height="600" class="w-50 py-3" src="{{photo.url}}" alt="" > </div>
    {% empty %}
      <div class="text-primary bg-light" align="center"><br>No Photos Uploaded</div>
    {% endfor %}
    <div align="right" class="bg-light py-5">
        <form action="{% url 'add_photo' destination.id %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <label>Caption: <input required type="text" id="caption" name="caption"></label>
            <button class="btn btn-dark" type="submit">Upload Photo</button>
        </form>
    </div>
</div>
<br>
<div class="bg-light py-5">
    <h3>Comments</h3>
    <div align="center"><a href="{% url "comments_create" destination_id=destination.id%}">Add Comment</a></div>
    {% for comment in destination.comment_set.all %}
        <div class="ps-2">
            <p class="small mb-0 text-primary">{{ comment.timestamp }}</p>
            <h5>{{ comment.user }}</h5>
            <p class="text-muted text-sm mb-2">{{ comment.comment|truncatewords:30 }}</p>
            <a class="reset-anchor text-sm" href="{% url 'comments_detail' comment.id %}">
                <i class="fas fa-share me-2 text-primary"></i><strong>show more</strong>
            </a>
            <br/>&nbsp;<br/>
        </div>
    {% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/destination_form.html
{% extends 'base.html' %}


{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Destination</h1>
  {% endif %}
  <form action="" method="post"> 
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn btn-dark">
  </form>
{% endblock %}

main_app/templates/main_app/destination_list.html
{% extends "base.html" %}
{% block content %}

<h1 align="center">Destinations</h1>
{% for destination in destination_list %}

<div class="row align-items-stretch gx-lg-0 py-3">
    <div class="col-lg-6 order-2 order-lg-1 bg-full-left">
      <div class="h-100 bg-light d-flex align-items-center">
        <div class="py-5 px-4">
          <h3 class="h4"> <a class="text-reset" href="{% url 'destinations_detail' destination.id %}">
                {{ destination.name }}
          </a></h3>
          <div class="text-muted">
            <p>{{destination.description|truncatewords:50}}</p>
          </div>
          <ul class="list-inline small text-uppercase mb-0">
            <li class="list-inline-item me-0 text-gray align-middle">By </li>
            <li class="list-inline-item align-middle me-0"><a class="fw-bold reset-anchor" href="#!">{{ destination.user.username }}</a></li>
            <li class="list-inline-item text-gray align-middle me-0">|</li>
            <li class="list-inline-item text-gray align-middle">{{ destination.timestamp }}</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-lg-6 order-1 order-lg-2"><a class="d-block h-100 bg-center bg-cover" href="{% url 'destinations_detail' destination.id %}" style="background: url({{destination.photo_set.first.url}})"></a></div>
  </div>
{% endfor %}
{% endblock %}

main_app/templates/main_app/destionation_form.html
{% extends 'base.html' %}


{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Destination</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/photo_list.html
{% extends "base.html" %}
{% block content %}

<div class="container pb-4">
  <header class="text-center mb-5">
    <h1>Gallery</h1>
  </header>
  <div class="row">
    {% for photo in photo_list %}
    <div class="col-lg-3 col-md-6 px-md-1 py-1">
      <a class="instagram-item d-block w-100 reset-anchor text-white" href="{% url 'destinations_detail' photo.destination.id %}">
        <img class="img-fluid img-thumbnail" src="{{ photo.url}}" alt="">
        <div class="instagram-item-overlay p-5">
          <h4>Visit {{photo.destination.name}}.</h4>
        </div>
      </a>
      <p>{{ photo.caption }}</p>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}